import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Counter App</title>
        <meta
          name="description"
          content="Generated by create next app + NextJS"
        />
        <link rel="icon" href="/react-icon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          mini <a href="https://reactjs.org/">react</a> apps!
        </h1>

        <p className={styles.description}>
          {" "}
          <code className={styles.code}>github.com/josh0x</code>
        </p>

        <div className={styles.grid}>
          <Link href="/counter">
            <a href="" className={styles.card}>
              <h2>Counter 🔢 &rarr;</h2>
              <p>
                The app uses patterns used in modern e-commerce shopping carts,
                and it renders content + CSS classes dynamically.
              </p>
            </a>
          </Link>

          <Link href="/counter">
            <a href="" className={styles.card}>
              <h2>Notes 📓 &rarr;</h2>
              <p>
                The app uses patterns used in modern e-commerce shopping carts,
                and it renders content + CSS classes dynamically.
              </p>
            </a>
          </Link>

          <Link href="/counter">
            <a href="" className={styles.card}>
              <h2>To Do ✅ &rarr;</h2>
              <p>
                The app uses patterns used in modern e-commerce shopping carts,
                and it renders content + CSS classes dynamically.
              </p>
            </a>
          </Link>

          <Link href="/counter">
            <a href="" className={styles.card}>
              <h2>Weather 🌤 &rarr;</h2>
              <p>
                The app uses patterns used in modern e-commerce shopping carts,
                and it renders content + CSS classes dynamically.
              </p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
